name: Generate Twitch Calendar

on:
  schedule:
    - cron: "0 0 */2 * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - run: pip install -r requirements.txt

      - name: Run script
        run: python main.py
        env:
          TWITCH_CLIENT_ID: ${{ secrets.TWITCH_CLIENT_ID }}
          TWITCH_TOKEN: ${{ secrets.TWITCH_TOKEN }}
          TWITCH_BROADCASTER_ID: ${{ secrets.TWITCH_BROADCASTER_ID }}

      - name: Commit calendar
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

          git add calendar.ics

          git commit -m "Update calendar" || echo "No changes"

          git pull --rebase origin main

          git push origin main